public with sharing class ProjectValidations {
    

}




/*Debe validarse que, al crear una tarea, la misma sea asignada a alguien que pertenezca al proyecto. Caso contrario mostrará un error.

No se debe permitir asignar Tareas si el estado del proyecto es diferente a “En Progreso”

No es necesaria alguna interfaz en particular o masiva para la creacion de Tareas.

Las tareas deben contemplar los estados “No Iniciada”, “En Progreso” y “Completada”.

El sistema no debe dejar pasar el proyecto a “Completado” en caso de que tenga tareas relacionadas con estado diferente de “Completada”.*/